refresh_rate: 10 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    filters:
      - kind: threshold
        level: info
  file:
    kind: file
    append: true
    path: "logs/file-{%Y-%m-%d_%H-%M-%S}.log"
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"
  step_ap:
    kind: rolling_file
    path: logs/step.log
    policy:
      trigger:
        kind: size
        limit: 10 kb
      roller:
        kind: fixed_window
        pattern: logs/step/step_{}.log
        count: 5
        base: 1
  rollingfile:
    kind: rolling_file
    append: true
    path: "logs/rolling_file.log"
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {m}{n}"
    policy:
      trigger:
        kind: time
        interval: 1 minute
      roller:
        kind: fixed_window
        pattern: "logs/old-rolling_file-{}.log"
        base: 0
        count: 20
root:
  level: info
  appenders:
    - stdout
    - step_ap