name: Rust

on:
  push:
    tags:
      - "publish-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Compress Published Files
        shell: sh
        run: ls -al && zip -qq -r ./publish_output.zip . -i ./target/debug && ls -al

      - name: publish
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish_output.zip
